#pragma once
#define _AFXDLL
#define _CRT_SECURE_NO_WARNINGS
#include <Afxwin.h>
#include <stdio.h>
#include <winsock2.h>
#include <conio.h> 
#include <list>
#include <iostream>
//#include <Windows.h>

#include <xlocale>
#include <xstring>
#include <codecvt>
#include <fstream>

#include <direct.h>
using namespace std;

#define DEFAULT_BUFLEN 4096

enum Flags
{
	//FLAG REGISTER
	REGISTER = 1,
	REGISTER_SUCCESS,
	REGISTER_FAILURE,

	//FLAG LOGIN
	LOGIN,
	LOGIN_SUCCESS,
	LOGIN_FAILURE,

	//FLAG CHANGE PASSWORD
	CHANGE_PASSWORD,
	CHANGE_PASSWORD_SUCCESS,
	CHANGE_PASSWORD_FAILURE,

	//FLAG CHECK USER

	//FIND
	CHECK_USER_FIND,
	USER_FIND_SUCCESS,
	USER_FIND_FAILURE,

	//ONLINE
	CHECK_USER_ONLINE,
	USER_ONLINE_SUCCESS,
	USER_ONLINE_FAILURE,

	//SHOW DATE
	CHECK_USER_SHOW_DATE,
	USER_SHOW_DATE_SUCCESS,
	USER_SHOW_DATE_FAILURE,

	//SHOW FULLNAME
	CHECK_USER_SHOW_FULLNAME,
	USER_SHOW_FULLNAME_SUCCESS,
	USER_SHOW_FULLNAME_FAILURE,

	//SHOW NOTE
	CHECK_USER_SHOW_NOTE,
	USER_SHOW_NOTE_SUCCESS,
	USER_SHOW_NOTE_FAILURE,

	//SHOW ALL INFO
	CHECK_USER_SHOW_ALL,
	USER_SHOW_ALL_SUCCESS,
	USER_SHOW_ALL_FAILURE,

	//FLAG SETUP INFORMATION

	//SETUP FULLNAME
	SETUP_INFO_FULLNAME,
	SETUP_INFO_FULLNAME_SUCCESS,
	SETUP_INFO_FULLNAME_FAILURE,

	//SETUP DATE
	SETUP_INFO_DATE,
	SETUP_INFO_DATE_SUCCESS,
	SETUP_INFO_DATE_FAILURE,

	//SETUP NOTE
	SETUP_INFO_NOTE,
	SETUP_INFO_NOTE_SUCCESS,
	SETUP_INFO_NOTE_FAILURE,

	//CHAT
	CREATE_CHAT,
	CREATE_CHAT_SUCCESS,
	CREATE_CHAT_FAILURE,
	CHAT,
	END_CHAT,

	//FILE
	SEND_FILE,
	SEND_FILE_ACCEPT,
	SEND_FILE_CANCEL,
	FILE_DATA,
	CONTINUE,
	STOP,

	DOWN_FILE,
	DOWN_FILE_CANCEL,
};
